spring:
  application:
    name: student
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5440/school_db?currentSchema=school}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

server:
  port: 8088